version: "3.9"

services:
    application:
        build: .
        networks:
            - mongodb-net
        ports:
            - "5000:5000"
        stdin_open: true    # docker run -i
        tty: true   # docker run -t
    mongodb:
        image: "mongo"
        networks:
            - mongodb-net
        volumes: 
            - type: volume
              source: mongodb-vol
              target: /data/db
            - type: volume
              source: mongodb_config-vol
              target: /data/configdb

networks: 
    mongodb-net:

volumes:
    mongodb-vol:
    mongodb_config-vol:
